import type { Config } from 'tailwindcss';
import {
  color,
  hue,
  syntax,
  space,
  layout,
  radius,
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
  letterSpacing,
  motion,
  border,
  breakpoint,
  icon,
  opacity,
  control,
} from '@mctlhq/tokens';

const families = (stack: string): string[] => stack.split(',').map((s) => s.trim());

// Reusable Tailwind preset. Token values are inlined at build time; accent /
// surface entries point at the runtime CSS variables from theme.css so the
// data-theme / data-accent flip works without rebuilding consumers.
const preset = {
  theme: {
    extend: {
      colors: {
        ink: { DEFAULT: color.ink, 2: color.ink2, 3: color.ink3 },
        line: { DEFAULT: color.line, strong: color.line2 },
        fg: { DEFAULT: color.fg, muted: color.fg2, subtle: color.fg3 },
        paper: {
          DEFAULT: color.paper,
          elevated: color.paperElevated,
          card: color.paperCard,
          ink: color.paperInk,
          fg: color.paperFg,
          line: color.paperLine,
          'line-strong': color.paperLineStrong,
        },
        terracotta: hue.terracotta,
        cyan: hue.cyan,
        lime: hue.lime,
        lilac: hue.lilac,
        surface: {
          bg: 'var(--surface-bg)',
          elevated: 'var(--surface-elevated)',
          card: 'var(--surface-card)',
          line: 'var(--surface-line)',
          'line-strong': 'var(--surface-line-strong)',
          fg: 'var(--surface-fg)',
          'fg-muted': 'var(--surface-fg-muted)',
          'fg-subtle': 'var(--surface-fg-subtle)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          highlight: 'var(--accent-highlight)',
          fg: 'var(--accent-fg)',
          soft: 'var(--accent-soft)',
          terracotta: 'var(--accent-terracotta)',
          cyan: 'var(--accent-cyan)',
          lime: 'var(--accent-lime)',
          vermilion: 'var(--accent-terracotta)',
          lilac: 'var(--accent-lilac)',
        },
        ok: 'var(--status-ok)',
        warn: 'var(--status-warn)',
        bad: 'var(--status-bad)',
        syntax: {
          key: syntax.key,
          string: syntax.string,
          number: syntax.number,
          keyword: syntax.keyword,
          punctuation: syntax.punctuation,
          comment: syntax.comment,
        },
      },
      fontFamily: {
        display: families(fontFamily.display),
        mono: families(fontFamily.mono),
        editorial: families(fontFamily.editorial),
      },
      fontWeight: {
        light: String(fontWeight.light),
        normal: String(fontWeight.regular),
        medium: String(fontWeight.medium),
        semibold: String(fontWeight.semibold),
        bold: String(fontWeight.bold),
      },
      fontSize: {
        marker: [fontSize.marker, { lineHeight: lineHeight.tight, letterSpacing: letterSpacing.marker }],
        body: [fontSize.body, { lineHeight: lineHeight.body }],
        lede: [fontSize.lede, { lineHeight: lineHeight.lede }],
        stat: [fontSize.stat, { lineHeight: lineHeight.none }],
        'section-title': [fontSize.sectionTitle, { lineHeight: lineHeight.sectionTitle }],
        hero: [fontSize.hero, { lineHeight: lineHeight.hero, letterSpacing: letterSpacing.hero }],
        xs: [fontSize.xs, { lineHeight: lineHeight.caption }],
        sm: [fontSize.sm, { lineHeight: lineHeight.caption }],
        base: [fontSize.base, { lineHeight: lineHeight.body }],
        md: [fontSize.md, { lineHeight: lineHeight.body }],
        lg: [fontSize.lg, { lineHeight: lineHeight.lede }],
        xl: [fontSize.xl, { lineHeight: lineHeight.lede }],
        '2xl': [fontSize['2xl'], { lineHeight: lineHeight.sectionTitle }],
        '3xl': [fontSize['3xl'], { lineHeight: lineHeight.sectionTitle }],
      },
      letterSpacing: {
        hero: letterSpacing.hero,
        marker: letterSpacing.marker,
      },
      spacing: {
        ...space,
        page: layout.pagePadding,
        section: layout.sectionPadding,
        gutter: layout.gutter,
        stack: layout.stack,
        prose: layout.proseWidth,
        pagew: layout.pageWidth,
      },
      maxWidth: {
        prose: layout.proseWidth,
        page: layout.pageWidth,
      },
      borderRadius: { ...radius },
      borderWidth: { ...border.width },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        overlay: 'var(--shadow-overlay)',
      },
      screens: { ...breakpoint },
      width: {
        'icon-xs': icon.xs,
        'icon-sm': icon.sm,
        'icon-md': icon.md,
        'icon-lg': icon.lg,
        'icon-xl': icon.xl,
      },
      height: {
        'icon-xs': icon.xs,
        'icon-sm': icon.sm,
        'icon-md': icon.md,
        'icon-lg': icon.lg,
        'icon-xl': icon.xl,
        'control-sm': control.height.sm,
        'control-md': control.height.md,
        'control-lg': control.height.lg,
      },
      opacity: { ...opacity },
      outlineWidth: { focus: 'var(--focus-ring-width)' },
      outlineOffset: { focus: 'var(--focus-ring-offset)' },
      transitionDuration: { ...motion.duration },
      transitionTimingFunction: { ...motion.easing },
    },
  },
} satisfies Partial<Config>;

export default preset;
