#!/usr/bin/env node
// Assembles the published CSS. theme.css is the self-contained artifact:
// raw token custom properties (from @mctlhq/tokens) inlined ahead of the
// semantic theme layer, so consumers need no @mctlhq/tokens at runtime.
import { readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const pkgRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const src = join(pkgRoot, 'src');
const dist = join(pkgRoot, 'dist');
const require = createRequire(import.meta.url);

const tokensCss = readFileSync(require.resolve('@mctlhq/tokens/tokens.css'), 'utf8');
const semanticCss = readFileSync(join(src, 'theme.css'), 'utf8');

writeFileSync(
  join(dist, 'theme.css'),
  `/* Generated by @mctlhq/css — raw tokens + semantic theme layer. */\n${tokensCss}\n${semanticCss}`,
);
copyFileSync(join(src, 'global.css'), join(dist, 'global.css'));
copyFileSync(join(src, 'prose.css'), join(dist, 'prose.css'));

console.log('css: wrote theme.css, global.css, prose.css');
